### ISSUE TITLE
[BUG] routes register

### ISSUE THREAD

**Issue by neo7337** [nandlabs/golly#42]
**Describe the bug**
Unable to add multiple handlers to same path with different handlers

**To Reproduce**
router.Post("/api/v1/users", handlers.AddUser(s.store))
router.Get("/api/v1/users", handlers.GetUsers(s.store))

**Expected behavior**
It should allow to register to the handlers as expected

**Screenshots**
![image](https://github.com/user-attachments/assets/54b0e52c-10b2-4245-9367-d3a1f6d2cd5c)

**Comment by nandagopalan** [comment]
Closed with #54
